name=7Semi MLX90393
version=1.0.0
author=7Semi
maintainer=7Semi <info@7semi.com>
sentence=MLX90393 3-axis magnetometer library
paragraph=Lightweight and configurable Arduino library for the MLX90393 sensor. Supports magnetic field measurement (µT), configurable gain, resolution, OSR, filter, and ESP32 custom I2C pins.
category=Sensors
url=https://github.com/7semi-solutions/7Semi-MLX90393
architectures=*
includes=7Semi_MLX90393.h
